global:
route:
  receiver: 'pushover'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
receivers:
- name: 'pushover'
  pushover_configs:
  - user_key: uqgy1rvtojbzckb1mqdmetypn7cxdo
    token: ajiyz8anj77xsupixzy8tscddmp2rh
